const normalize = require('./normalize')

describe('normalize', () => {

    test('presentation forms', () => {

        expect(normalize('ﬠ')).toBe('ע')
        expect(normalize('ﬡ')).toBe('א')
        expect(normalize('ﬢ')).toBe('ד')
        expect(normalize('ﬣ')).toBe('ה')
        expect(normalize('ﬤ')).toBe('כ')
        expect(normalize('ﬥ')).toBe('ל')
        expect(normalize('ﬦ')).toBe('ם')
        expect(normalize('ﬧ')).toBe('ר')
        expect(normalize('ﬨ')).toBe('ת')
        // expect(normalize('﬩')).toBe('?')
        expect(normalize('שׁ')).toBe('שׁ')
        expect(normalize('שׂ')).toBe('שׂ')
        expect(normalize('שּׁ')).toBe('שּׁ')
        expect(normalize('שּׂ')).toBe('שּׂ')
        expect(normalize('אַ')).toBe('אַ')
        expect(normalize('אָ')).toBe('אָ')

        expect(normalize('אּ')).toBe('אּ')
        expect(normalize('בּ')).toBe('?')
        expect(normalize('גּ')).toBe('?')
        expect(normalize('דּ')).toBe('?')
        expect(normalize('הּ')).toBe('?')
        expect(normalize('וּ')).toBe('?')
        expect(normalize('זּ')).toBe('?')
        expect(normalize('טּ')).toBe('?')
        expect(normalize('יּ')).toBe('?')
        expect(normalize('ךּ')).toBe('?')
        expect(normalize('כּ')).toBe('?')
        expect(normalize('לּ')).toBe('?')
        expect(normalize('מּ')).toBe('?')
        expect(normalize('נּ')).toBe('?')
        expect(normalize('סּ')).toBe('?')
        expect(normalize('ףּ')).toBe('?')
        expect(normalize('פּ')).toBe('?')
        expect(normalize('צּ')).toBe('?')
        expect(normalize('קּ')).toBe('?')
        expect(normalize('רּ')).toBe('?')
        expect(normalize('שּ')).toBe('?')
        expect(normalize('תּ')).toBe('?')
        expect(normalize('וֹ')).toBe('?')
        expect(normalize('בֿ')).toBe('?')
        expect(normalize('כֿ')).toBe('?')
        expect(normalize('פֿ')).toBe('?')
        expect(normalize('ﭏ')).toBe('?')
    })
})
